package com.coc.cu.domain

enum class AccountType {
    SAVINGS,
    LOAN,
}

enum class AuthProvider{
    FACEBOOK,
    GOOGLE
}

enum class TransactionType {
    CARD,
    SAVINGS,
    SAVINGS_CHEQUE,
    SHARES,
    SHARES_CHEQUE,
    WITHDRAWAL,
    WITHDRAWAL_CHEQUE,
    LOAN,
    LOAN_CHEQUE,
    LOAN_REPAYMENT,
    LOAN_REPAYMENT_CHEQUE,
    INTEREST_ON_LOAN,
    INTEREST_ON_LOAN_CHEQUE,
    STATIONERY,
    STATIONERY_CHEQUE,
    TRANSPORT,
    INCENTIVE_TO_PERSONNEL,
    INCENTIVE_TO_PERSONNEL_CHEQUE,
    OPENING_BALANCE,
    OPENING_LOAN_BALANCE,

}